[package]
name = "heh"
version = "0.1.0"
authors = ["arsen <arsenchechen@yahoo.com>"]
edition = "2018"

[dependencies]
vk_api = { git = "https://github.com/Arsen-chechen/vk_api"}
serde_json = "1.0"
rand = "0.6.5"